# Generated by Django 4.1.4 on 2022-12-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_ratings', models.FloatField(default=0)),
                ('course_reviews', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=250)),
                ('course_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursefinder.course')),
            ],
        ),
    ]
